### ISSUE TITLE
ContinousCapture with MVacquire

### ISSUE THREAD

**Issue by patzhang** [geggo/MVacquire#10]
Hi geggo,

Sorry to bother you. This MVacquire project is very useful and I used it to capture single images successfully. 

I have read the intro and tutorials, but I am still not sure about the following question.  This is not an issue, just a question I wonder if you can help.

Does MVacquire support the Continuous Capture, which is like the example in the following page?
https://www.matrix-vision.com/manuals/SDK_CPP/ContinuousCapture_8cpp-example.html

Many thanks.

**Comment by geggo** [comment]
Hi,
MVacquire works well with continuous acquisition, but it does not contain a ready made solution for this. Essentially, all you need is to repeat the command sequence for a single image acquisition in a loop. Best put this in a separate thread and send the result via a Queue to the main thread. When I am back to my camera setup I will add some more details to the docs with more details and example code. Ping me again if I get lazy and forget about it.

Gregor

**Comment by alertbird** [comment]
Many thanks for your reply. It is very good to know MVacquire works well with continuous acquisition. I am looking forward to some docs and example code. It will be very very useful.

**Comment by geggo** [comment]
Hi,
I added a new  [demo program for continuous acquisition](https://github.com/geggo/MVacquire/test_continuous_acquisition.py). Hope that helps to get started.

Gregor

**Comment by alertbird** [comment]
Hi Gregor,

Thanks a lot for adding the demo code so quickly. It is a lot better than what I have so far. I will try your code and tweak mine. 

Thanks,
Patrick
