### ISSUE TITLE
Continuous Acquisition timeout

### ISSUE THREAD

**Issue by Mersina** [geggo/MVacquire#11]
Hi, 

I'm trying to implement continuous acquisition and display the images in a Python Tkinter application. 
I am getting a timeout after acquiring about 350 images. Do you have any suggestions for the timeout setting to change in order to run the acquisition for longer (ideally until the application is closed.) 

Thanks! 

Mersina

**Comment by geggo** [comment]
Did you follow the approach demonstrated in test_continuous_acquisition?
