### ISSUE TITLE
Change Camera Exposure Time 

### ISSUE THREAD

**Issue by Mersina** [geggo/MVacquire#12]
Hi, 

Is there a way to edit the exposure time using the tree structure? 
I am looking for a convenient way to change the exposure time, such as: device.Setting.Base.Camera.Expose_us. 

Thanks! 

Mersina

**Comment by geggo** [comment]
The name for the exposuRe setting is device dependent, just search for it, a typical place is in device.setting.base.camera.acquisitioncontrol.exposuretime

**Comment by Mersina** [comment]
Hi I found this -- thanks for getting back.
