### ISSUE TITLE
Error in tutorial "Can't get correct response with "dmg."

### ISSUE THREAD

**Issue by sriramyab** [geggo/MVacquire#5]
Hello, 
 I am trying to install the "MVacquire" on my ubuntu laptop. So that i can establish serial communication from my bluefox camera to my laptop. 

Steps that I followed:
1. Downloaded "mvBlueFOX-x86_64_ABI2-2.15.0.tgz" from the matrix-vision website and also install_mvBlueFOX.sh
2. Ran the command ./install_mvBlueFOX.sh to install all the mvimpact_acquire dirs. 
3. Then i verified the "wxPropview". I can access the camera through that. It works fine. 
![propview](https://cloud.githubusercontent.com/assets/6140138/14066726/b4d0001e-f417-11e5-8f89-e44437ffff15.png)
4. Downloaded the zip file from "https://github.com/geggo/MVacquire/tree/96a1a103ba6eec6d285eaefd929b83a9e13cbc6d"
5. I also checked using "printenv" to make sure I have the "MVIMPACT_ACQUIRE_DIR" as an environment variable. 
![printenv](https://cloud.githubusercontent.com/assets/6140138/14066751/2fdd8146-f418-11e5-9d9c-cf18d6c05ae8.png)
6. Then I ran the setup.py file with the following modifications:
![setup](https://cloud.githubusercontent.com/assets/6140138/14066747/1ebc03b0-f418-11e5-95b4-641eb2b07caf.png)
7. After the setup process completes I get no errors as can be seen below. 
![aftersetup](https://cloud.githubusercontent.com/assets/6140138/14066750/2dd02390-f418-11e5-933c-758072637b17.png)
8. But when i go to the tutorial page and run the commands "from mv import dmg" and "dmg."
![dmg](https://cloud.githubusercontent.com/assets/6140138/14066758/5d06b656-f418-11e5-9505-1996b0da659e.png)

This is where I am stuck and this is probably the reason for my errors as described in the previous thread (https://github.com/geggo/MVacquire/issues/3). I would be glad if someone could point where I am going wrong. 

Thanks

**Comment by uhagi** [comment]
Did you use the TAB key as described...?


>>In an IPython shell, try typing 'dmg.' and hit TAB:

regards
Uwe

**Comment by sriramyab** [comment]
Yeah I did. I don't think the "dmg." part is installed correctly. I can't get any suggestions/extensions when I hit TAB..

I ran the c codes given in the acquire library as example. They work fine. I also tried communication using the ROS nodes they also work fine. So , I think the camera part is good.

**Comment by geggo** [comment]
Since you are able to import mv and access the device manager (mv.dmg) I think that the Python wrapper is ok. Please try to play around with the following commands from the tutorial in a freshly started Python (or IPython/Jupyter) console to get access to your device (of course with camera plugged in)

```
   import mv
   print mv.dmg.device_count
   print mv.dmg.get_device_list()
   dev = mv.dmg.get_device('25001103')

   dev. #press TAB
```

**Comment by jakeboydston** [comment]
I am now too at this point. I am getting error messages when attempting your last reply.
![capture](https://cloud.githubusercontent.com/assets/10642629/16464208/cc99174a-3dfe-11e6-8356-c685eff792ea.PNG)
While my device is usable in PropView
![capture](https://cloud.githubusercontent.com/assets/10642629/16464264/fcb3c79a-3dfe-11e6-8dff-84771cecce20.PNG)

**Comment by geggo** [comment]
Strange, it seems the conversion from the C device info struct to a Python dict goes wrong, cython takes care of this. Other parts of the wrapper seem ok. I see you are running a 32bit Python. What is your system configuration, which compiler did you use to build the wrapper?

**Comment by a0209371** [comment]
![29703730](https://cloud.githubusercontent.com/assets/3858191/16506016/707cc744-3ee5-11e6-88f6-ab7b308d0dc2.JPG)
![vd000001](https://cloud.githubusercontent.com/assets/3858191/16506015/703f4bf8-3ee5-11e6-83b7-3126a817db30.JPG)
I'm working with Jake.  The camera and virtual machines are listed and accessible but the script barfs when it attempts to access the camera which has an integer only serial number returning the "PROPHANDLING_COMPONENT_ID_INVALID" error

**Comment by geggo** [comment]
You get this error because the script (testmv.py?) tries to access camera
features that are only present for the virtual camera devices. If you want
to test real hardware, just remove those calls.

Gregor

a0209371 <notifications@github.com> schrieb am Fr., 1. Juli 2016 um 00:15:

**Comment by geggo** [comment]
@jakeboydston @sriramyab 
I fixed a bug in the wrapper within get_device_list(), which fixes the problems, including dmg.+TAB issue.

**Comment by alertbird** [comment]
Hi @geggo,

Thanks for the fix. What is the best way to update to the latest version? Is it just checking out the latest code and install again?
python setup.py install

Thanks.

**Comment by geggo** [comment]
> Am 11.11.2016 um 10:45 schrieb alertbird <notifications@github.com>:
> 
> Hi @geggo <https://github.com/geggo>,
> 
> Thanks for the fix. What is the best way to update to the latest version? Is it just checking out the latest code and install again?
> python setup.py install
> 
> 
Yes, hopefully this should do the job.
