### ISSUE TITLE
Linux 32bit 

### ISSUE THREAD

**Issue by roipony** [geggo/MVacquire#6]
Hi
it possible to get the package for the 32 -bit version of Linux.
would you also send  the binaries for 32bit and python 2.7.

thank you very match

**Comment by geggo** [comment]
sorry, I have no development system available for 32 bit Linux, but anyhow, on Linux building the package yourself is (should be) straightforward and is the recommended way for installation:

1. install mvIMPACT Acquire library
2. update search path to point to mvIMPACT Acquire library
3. edit `setup.py` to point to mvIMPACT Acquire installation location
4. for complete build: 
    `python setup.py install`
