### ISSUE TITLE
Cannot Build/Install

### ISSUE THREAD

**Issue by jakeboydston** [geggo/MVacquire#7]
Hello,

I cannot build nor install this package on my computer. The message I get is:

> 
running build
running built_ext
skipping '_mvDeviceManager.c' Cython extension (up-to-date)
building 'mv' extension
error: Unable to find vcvarsall.bat
> 

I've googled for this and cannot solve the issue. Can you please help?

**Comment by geggo** [comment]
This means you have no C compiler installed, or it cannot be found. Did you follow the instructions in README.rst or docs/intro.rst ? What is your system configuration?

**Comment by jakeboydston** [comment]
I did read both, and I'm worried that I have conflicting compilers now. I have a 64-bit Intel Core i5 Windows 7 computer.

**Comment by geggo** [comment]
Having several compilers installed is not an issue, if you use the 'Visual C++ 2008 64-bit Command Prompt' then all the settings are prepared such that you use the right one (for Python 2.7). I noticed that the line wrapping in README.rst is screwed up, just fixed this. Are you using plain python 2.7 from python.org?

**Comment by jakeboydston** [comment]
I believe I've gotten the package to install. Thank you for your help.
