### ISSUE TITLE
Binaries or help with WinPython

### ISSUE THREAD

**Issue by hausler89** [geggo/MVacquire#8]
Hey,

I tried to make the project with WinPython (cython), but it won't compile.

Could somebody maybe provide me a binary fror 2.7, or help me with compiling it?

Error message:

``running build
running build_ext
skipping '_mvDeviceManager.c' Cython extension (up-to-date)
building 'mv' extension
C:\Users\praktgo\Desktop\Sascha\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\Scripts\gcc.exe -mdll -O -Wall "-IC:\Program Files (x86)\MATRIX VISION\mv
IMPACT acquire" -IC:\Users\praktgo\Desktop\Sascha\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\include -IC:\Users\praktgo\Desktop\Sascha\WinPython-64b
it-2.7.10.3\python-2.7.10.amd64\PC -c _mvDeviceManager.c -o build\temp.win-amd64-2.7\Release_mvdevicemanager.o
_mvDeviceManager.c: In function '__pyx_pf_2mv_13DeviceManager_6get_device_list':
_mvDeviceManager.c:3420:5: warning: implicit declaration of function 'DMR_GetDeviceInfoEx' [-Wimplicit-function-declaration]
     __pyx_t_4 = __pyx_f_2mv_dmr_errcheck(DMR_GetDeviceInfoEx(__pyx_v_hdev, dmditDeviceInfoStructure, (&__pyx_v_device_info), (&__pyx_v_ssize))); if (
unlikely(__pyx_t_4 == 1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto **pyx_L1_error;}
     ^
_mvDeviceManager.c:3420:76: error: 'dmditDeviceInfoStructure' undeclared (first use in this function)
     __pyx_t_4 = __pyx_f_2mv_dmr_errcheck(DMR_GetDeviceInfoEx(__pyx_v_hdev, dmditDeviceInfoStructure, (&__pyx_v_device_info), (&__pyx_v_ssize))); if (
unlikely(__pyx_t_4 == 1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE**; goto **pyx_L1_error;}
                                                                            ^
_mvDeviceManager.c:3420:76: note: each undeclared identifier is reported only once for each function it appears in
_mvDeviceManager.c: In function '__pyx_pf_2mv_6Device_20start_acquisition':
_mvDeviceManager.c:5592:3: warning: implicit declaration of function 'DMR_AcquisitionStart' [-Wimplicit-function-declaration]
   __pyx_t_1 = __pyx_f_2mv_dmr_errcheck(DMR_AcquisitionStart(__pyx_v_self->drv)); if (unlikely(__pyx_t_1 == 1)) {__pyx_filename = __pyx_f[0]; __pyx_li
neno = 283; __pyx_clineno = __LINE**; goto **pyx_L1_error;}
   ^
_mvDeviceManager.c: In function '__pyx_pf_2mv_6Device_22stop_acquisition':
_mvDeviceManager.c:5651:3: warning: implicit declaration of function 'DMR_AcquisitionStop' [-Wimplicit-function-declaration]
   __pyx_t_1 = __pyx_f_2mv_dmr_errcheck(DMR_AcquisitionStop(__pyx_v_self->drv)); if (unlikely(__pyx_t_1 == 1)) {__pyx_filename = __pyx_f[0]; __pyx_lin
eno = 286; __pyx_clineno = __LINE**; goto **pyx_L1_error;}
   ^
_mvDeviceManager.c: In function '__pyx_pf_2mv_11ImageResult_4get_buffer':
_mvDeviceManager.c:6546:62: error: 'ibpfBGR888Packed' undeclared (first use in this function)
   __pyx_t_4 = __Pyx_PyInt_From_enum__TImageBufferPixelFormat(ibpfBGR888Packed); if (unlikely(!__pyx_t_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno
= 389; __pyx_clineno = __LINE**; goto **pyx_L1_error;}
                                                              ^
_mvDeviceManager.c:6558:62: error: 'ibpfYUV444Packed' undeclared (first use in this function)
   __pyx_t_4 = __Pyx_PyInt_From_enum__TImageBufferPixelFormat(ibpfYUV444Packed); if (unlikely(!__pyx_t_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno
= 390; __pyx_clineno = __LINE**; goto **pyx_L1_error;}
                                                              ^
_mvDeviceManager.c: In function '__pyx_f_2mv_9Component_get_string':
_mvDeviceManager.c:7180:119: warning: passing argument 4 of 'OBJ_GetSWithInplaceConstruction' from incompatible pointer type
   __pyx_t_1 = __pyx_f_2mv_obj_errcheck(OBJ_GetSWithInplaceConstruction(__pyx_v_self->obj, __pyx_v_sq, (&__pyx_v_res), __pyx_f_2mv_StringConstructionF
unction, 0, __pyx_v_index)); if (unlikely(__pyx_t_1 == 1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 494; __pyx_clineno = __LINE**; goto **pyx_L1_e
rror;}
                                                                                                                       ^
In file included from _mvDeviceManager.c:241:0:
C:\Program Files (x86)\MATRIX VISION\mvIMPACT acquire/mvDeviceManager/Include/mvDeviceManager.h:751:31: note: expected 'char \* (*)(const char *, size_
t)' but argument is of type 'char \* (_)(char *, size_t)'
  TPROPHANDLING_ERROR DMR_CALL OBJ_GetSWithInplaceConstruction( HOBJ hObj, TOBJ_StringQuery sq, char_\* pResult, SCF constructionFunc, int mode, int re
served );
                               ^
_mvDeviceManager.c: In function '__pyx_pf_2mv_9Component_12display_name___get**':
_mvDeviceManager.c:7337:109: error: 'sqObjDisplayName' undeclared (first use in this function)
   __pyx_t_1 = ((struct __pyx_vtabstruct_2mv_Component *)__pyx_v_self->__pyx_vtab)->get_string(__pyx_v_self, sqObjDisplayName, NULL); if (unlikely(!__
pyx_t_1)) {**pyx_filename = __pyx_f[0]; __pyx_lineno = 510; __pyx_clineno = __LINE**; goto **pyx_L1_error;}
                                                                                                             ^
_mvDeviceManager.c: In function '__pyx_pf_2mv_9Component_9isvisible___get**':
_mvDeviceManager.c:7602:3: error: unknown type name 'TComponentVisibility'
   TComponentVisibility __pyx_v_visibility;
   ^
_mvDeviceManager.c:7619:3: warning: implicit declaration of function 'OBJ_GetVisibility' [-Wimplicit-function-declaration]
   __pyx_t_1 = __pyx_f_2mv_obj_errcheck(OBJ_GetVisibility(__pyx_v_self->obj, (&__pyx_v_visibility))); if (unlikely(__pyx_t_1 == 1)) {__pyx_filename =
__pyx_f[0]; __pyx_lineno = 529; __pyx_clineno = __LINE__; goto **pyx_L1_error;}
   ^
_mvDeviceManager.c: In function '__pyx_pf_2mv_8Property_12getS':
_mvDeviceManager.c:11107:3: warning: implicit declaration of function 'OBJ_GetSFormattedEx' [-Wimplicit-function-declaration]
   __pyx_t_1 = __pyx_f_2mv_obj_errcheck(OBJ_GetSFormattedEx(__pyx_v_self->__pyx_base.obj, NULL, (&__pyx_v_bufsize), NULL, __pyx_v_index)); if (unlikel
y(__pyx_t_1 == 1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 710; __pyx_clineno = __LINE**; goto __pyx_L1_error;}
   ^
_mvDeviceManager.c: In function '__pyx_f_2mv_11PropertyPtr_get':
_mvDeviceManager.c:13515:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   __pyx_r = ((long)__pyx_v_value);
              ^
_mvDeviceManager.c: In function 'initmv':
_mvDeviceManager.c:29032:34: error: 'cvGuru' undeclared (first use in this function)
   __pyx_v_2mv_visibility_level = cvGuru;
                                  ^
_mvDeviceManager.c: In function '__Pyx_RaiseArgtupleInvalid':
_mvDeviceManager.c:29706:18: warning: unknown conversion type character 'z' in format [-Wformat=](num_expected == 1) ? "" : "s", num_found);
                  ^
_mvDeviceManager.c:29706:18: warning: format '%s' expects argument of type 'char *', but argument 5 has type 'Py_ssize_t' [-Wformat=]
_mvDeviceManager.c:29706:18: warning: unknown conversion type character 'z' in format [-Wformat=]
_mvDeviceManager.c:29706:18: warning: too many arguments for format [-Wformat-extra-args]
_mvDeviceManager.c: In function '__Pyx_RaiseTooManyValuesError':
_mvDeviceManager.c:30746:18: warning: unknown conversion type character 'z' in format [-Wformat=]
                  "too many values to unpack (expected %" CYTHON_FORMAT_SSIZE_T "d)", expected);
                  ^
_mvDeviceManager.c:30746:18: warning: too many arguments for format [-Wformat-extra-args]
_mvDeviceManager.c: In function '__Pyx_RaiseNeedMoreValuesError':
_mvDeviceManager.c:30752:18: warning: unknown conversion type character 'z' in format [-Wformat=]
                  index, (index == 1) ? "" : "s");
                  ^
_mvDeviceManager.c:30752:18: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'Py_ssize_t' [-Wformat=]
_mvDeviceManager.c:30752:18: warning: too many arguments for format [-Wformat-extra-args]
_mvDeviceManager.c: In function '__Pyx_BufFmt_ProcessTypeChunk':
_mvDeviceManager.c:34047:26: warning: unknown conversion type character 'z' in format [-Wformat=]
                          ctx->head->field->type->arraysize[0], ctx->enc_count);
                          ^
_mvDeviceManager.c:34047:26: warning: unknown conversion type character 'z' in format [-Wformat=]
_mvDeviceManager.c:34047:26: warning: too many arguments for format [-Wformat-extra-args]
_mvDeviceManager.c:34099:20: warning: unknown conversion type character 'z' in format [-Wformat=](Py_ssize_t)ctx->fmt_offset, (Py_ssize_t)offset);
                    ^
_mvDeviceManager.c:34099:20: warning: unknown conversion type character 'z' in format [-Wformat=]
_mvDeviceManager.c:34099:20: warning: too many arguments for format [-Wformat-extra-args]
_mvDeviceManager.c: In function '__pyx_buffmt_parse_array':
_mvDeviceManager.c:34161:25: warning: unknown conversion type character 'z' in format [-Wformat=]
                         ctx->head->field->type->arraysize[i], number);
                         ^
_mvDeviceManager.c:34161:25: warning: format '%d' expects argument of type 'int', but argument 3 has type 'size_t' [-Wformat=]
_mvDeviceManager.c:34161:25: warning: too many arguments for format [-Wformat-extra-args]
_mvDeviceManager.c: In function '__Pyx_GetBufferAndValidate':
_mvDeviceManager.c:34346:7: warning: unknown conversion type character 'z' in format [-Wformat=]
       dtype->name, (Py_ssize_t)dtype->size, (dtype->size > 1) ? "s" : "");
       ^
_mvDeviceManager.c:34346:7: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'Py_ssize_t' [-Wformat=]
_mvDeviceManager.c:34346:7: warning: unknown conversion type character 'z' in format [-Wformat=]
_mvDeviceManager.c:34346:7: warning: too many arguments for format [-Wformat-extra-args]
error: command 'C:\Users\praktgo\Desktop\Sascha\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\Scripts\gcc.exe' failed with exit status 1

C:\Users\praktgo\Desktop\Sascha\MVacquire-master>``

**Comment by geggo** [comment]
Have no idea about how to compile with WinPython. I see two problems: it seems you try to build with outdated 32bit camera drivers installed, this likely will fail. Please check that you have recent 64bit camera drivers installed. Also check that the environment vars pointing to the drivers (for details see setup.py) are correct.

Gregor
